### ISSUE TITLE
[BUG] Failed to GetMapTimeLeft() without any apparent reason

### ISSUE THREAD

**Issue by olokos** [Kxnrl/Mapchooser-Redux#35]
![Bug picture](https://cdn.discordapp.com/attachments/379572504542445568/702540096448102400/unknown.png)

Additionally when used on surf server it generates "null" automatically for each map, which doesn't look right.

![Nulls](https://media.discordapp.net/attachments/379572504542445568/702540569582501889/unknown.png?width=383&height=524)

Other than that, great work, thank you!

**Comment by Kxnrl** [comment]
null -> the map description defined in mapdata.kv
Failed to get timeleft is no problem, it will display on map start?

**Comment by olokos** [comment]
Well, mapdata is automatically generated, isn't it?
It seems to be a bit of a problem, since !timeleft doesn't work and every map is set to 1 hour.

Not sure how much this is a problem on my side and how much is it on the plugins side, really, but with UMC mapchooser I could have my map times based on tiers, !timeleft used to work (probably) and definitely there were no nulls in nominate.

**Comment by Kxnrl** [comment]
mapdata is automatically generate on each mapstart.
did you use mp_maxrounds convar?

**Comment by Kxnrl** [comment]
easy to check that with u change mp_timelimit , if console print failed, write to me.

**Comment by olokos** [comment]
I haven't used any convars apart from those set as defaults to be honest.

**Comment by Kxnrl** [comment]
mp_ convars define in gamemode_{your gamemod}_{server?}.cfg by default

**Comment by olokos** [comment]
I'm more concerned by the GetMapTimeLeft() issue than anything else, really, as this bug is constantly appearing in console. 😄

**Comment by Kxnrl** [comment]
of course, but tell me about mp_maxrounds and mp_timelimit, I can help you about that. because MCR does not work with round limit mode. just for time limit mode.

**Comment by Kxnrl** [comment]
when appearing  in console, type timeleft and press enter, check the output.

**Comment by olokos** [comment]
I mean my server has been running for hours without hibernating and it's still on the initial map :(
timeleft in console shows a valid time
https://prnt.sc/s49rlj
But !timeleft does nothing, neither in char nor in server console.

mp_maxrounds 1
mp_timelimit 60

Having that said, umc mapchooser has the awesome ability to manually set the mp_timelimit based on the map tier, which is set manually by hand in its config files.

But umc mapchooser keeps loading from files so !nominate lags server and it actually doesn't add anything automatically, so yeah, I'll leave it to the past. 😄 

My server is @ https://kiepownica.pl

**Comment by Kxnrl** [comment]
may be something broken that.

**Comment by cheesea3** [comment]
> I mean my server has been running for hours without hibernating and it's still on the initial map :(
> timeleft in console shows a valid time
> https://prnt.sc/s49rlj
> But !timeleft does nothing, neither in char nor in server console.
> 
> mp_maxrounds 1
> mp_timelimit 60
> 
> Having that said, umc mapchooser has the awesome ability to manually set the mp_timelimit based on the map tier, which is set manually by hand in its config files.
> 
> But umc mapchooser keeps loading from files so !nominate lags server and it actually doesn't add anything automatically, so yeah, I'll leave it to the past. 😄
> 
> My server is @ https://kiepownica.pl

Late, however as aforementioned by @Kxnrl, the plugin is not compatible with RoundLimit and so you should try setting the CONVAR 'mp_maxrounds 1' to 0 in csgo/cfg/server.cfg. In your latest screenshot, it shows that the time left until the next map is dependent on either TimeLimit or MaxRound, whichever comes first.

For an extra step, add mp_ignore_round_win_conditions 1, this allows the mapchooser plugin to change the map without the condition of the round getting in the way.

The plugin is loosely coupled and so if you're having a problem with 'GetMapTimeLeft()' then you should double-check to see if you have 'forcemapend_redux.smx', which is the one that references that Sourcemod function.

My last thoughts are that you might not even have an issue. Either you have rounds and times going concurrently, or the GetMapTimeLeft function is returning as infinite since there are no players for the server to process any frames. The latter would only be the case if you and Mettbrochen were the first ones to connect and the server was empty prior to that error in your console.

Hope this helps, I confirmed the plugin to be working on my dev server with a default configuration in addition to the CONVAR changes I brought up above.

**Comment by olokos** [comment]
I did use `forcemapend_redux.smx`, but I guess this mapchooser isn't that compatible, so I've decided to choose another.

Not sure if we should close this issue or not, as this is still a potential enhancement in the future

**Comment by Kxnrl** [comment]
Fixed at latest version.
