### ISSUE TITLE
How does mappool.kv work?

### ISSUE THREAD

**Issue by oylsister** [Kxnrl/Mapchooser-Redux#37]
Hi, I just wonder that I can't find any file that have name mappool.kv. I just really don't get it how mappool is work.

**Comment by Kxnrl** [comment]
map pool in {sourcemod path}/data/mappool.kv
it's map cooldown data .

**Comment by oylsister** [comment]
yeah, but after I launch the server with that plugin it seem like not to create that file even the end of the map.

**Comment by Kxnrl** [comment]
yes. it requires players in game to calculate cooldown.

**Comment by sashajov** [comment]
Hi :) Is there a way to manually change values in mappool.kv? When I change some value, after map change just back to the old values. So I can't reset cooldowns :)

Also, I noticed when you manually play one map a few more times, cooldown just increasing every time for that map. Is there a way to limit that feature that can increase only to predefined max cooldown, so admin can change manually maps sometimes without fear of the server crash. If you manually play few times one map, the mapchooser will increase a cooldown, it looks like mapchooser try to change to that map, but got an error FailedGetMap (maybe because of over increased CD) or something like that and back to default map. Then it looks like a server crash. It also seems strange to me, do you have any idea what the problem might be.

Maybe I did something wrong, so maybe I just need advice.

I really like this plugin, so I will try everything to fix these things. :)

Thanks in advance. <3

**Comment by Kxnrl** [comment]
> Hi :) Is there a way to manually change values in mappool.kv? When I change some value, after map change just back to the old values. So I can't reset cooldowns :)
> 
> Also, I noticed when you manually play one map a few more times, cooldown just increasing every time for that map. Is there a way to limit that feature that can increase only to predefined max cooldown, so admin can change manually maps sometimes without fear of the server crash. If you manually play few times one map, the mapchooser will increase a cooldown, it looks like mapchooser try to change to that map, but got an error FailedGetMap (maybe because of over increased CD) or something like that and back to default map. Then it looks like a server crash. It also seems strange to me, do you have any idea what the problem might be.
> 
> Maybe I did something wrong, so maybe I just need advice.
> 
> I really like this plugin, so I will try everything to fix these things. I don't wanna change mapchooser :D
> 
> Thanks in advance. <3

u mean map attribute? It defined in mapdata.kv.  If you wanna reset/remove cooldown, just using sm_clearallcd/sm_clearmapcd/sm_resetmapcd 
all commands in https://github.com/Kxnrl/Mapchooser-Redux/blob/master/mapchooser/cmds.sp.

**Comment by sashajov** [comment]
Thanks a lot, that was exactly what I need. :)

**Comment by oylsister** [comment]
Alright after seeing how the plugins work, I could say that MapChooser-Redux is a great plugin that I always looking for. Btw let me leave some small request here for your further update (if you like to update more).

- Nominations List or !nomlist (Right Now I can only adapted the code from mapchooser-extended to work with Redux version)
- !enablertv and !disablertv (Small feature, even that is so easy to write)
